---
sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
bundler_args: '--without debug --jobs 3'

before_install:
  - gem install bundler

rvm:
  - 2.5.2

branches:
  only:
    - master

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn
  - bundle exec rails db:migrate

jobs:
  include:
    - stage: test
      script: 'bin/ci.rb'
      env:
        - RUN=test

notifications:
  email: true
  on_success: change
  on_failure: always
  notify: true
